# Generated by Django 4.0.4 on 2022-04-26 19:23

from django.db import migrations, models
import school_api_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
            ],
            bases=(models.Model, school_api_app.models.FieldNamesMixin),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('credits', models.IntegerField()),
                ('students', models.ManyToManyField(blank=True, related_name='courses', to='school_api_app.student')),
            ],
            bases=(models.Model, school_api_app.models.FieldNamesMixin),
        ),
    ]
